export default {
    KINDE_ISSUER_URL: "Your KINDE_ISSUER_URL ",
    KINDE_POST_CALLBACK_URL: "Your KINDE_POST_CALLBACK_URL",
    KINDE_CLIENT_ID: "Your KINDE_CLIENT_ID",
    KINDE_POST_LOGOUT_REDIRECT_URL: "Your KINDE_POST_LOGOUT_REDIRECT_URL",


} 